//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoryes
    {
        public Categoryes()
        {
            this.Categoryes1 = new HashSet<Categoryes>();
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<Categoryes> Categoryes1 { get; set; }
        public virtual Categoryes Categoryes2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
