//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public Nullable<int> PackegeId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Packeges Packeges { get; set; }
    }
}
